name: flutter_baby_name_sdk
description: "This flutter baby name sdk provides lots of baby names."
version: 0.0.1
homepage: https://github.com/ramkishoreprajapat/learning/tree/main/flutter_baby_name_sdk/flutter_baby_name_sdk

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/BabyNamesDB.sqlite
